//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DisplayNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DisplayNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lisa.Kiwi.Web.Reporting.App_GlobalResources.Resources.DisplayNames", typeof(DisplayNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacten.
        /// </summary>
        public static string ReportContacts {
            get {
                return ResourceManager.GetString("ReportContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aangemaakt.
        /// </summary>
        public static string ReportCreated {
            get {
                return ResourceManager.GetString("ReportCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beschrijving.
        /// </summary>
        public static string ReportDescription {
            get {
                return ResourceManager.GetString("ReportDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ip.
        /// </summary>
        public static string ReportIp {
            get {
                return ResourceManager.GetString("ReportIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locatie.
        /// </summary>
        public static string ReportLocation {
            get {
                return ResourceManager.GetString("ReportLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum incident.
        /// </summary>
        public static string ReportTime {
            get {
                return ResourceManager.GetString("ReportTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string ReportType {
            get {
                return ResourceManager.GetString("ReportType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pesten.
        /// </summary>
        public static string ReportTypeBullying {
            get {
                return ResourceManager.GetString("ReportTypeBullying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inbraak.
        /// </summary>
        public static string ReportTypeBurglary {
            get {
                return ResourceManager.GetString("ReportTypeBurglary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digitaal.
        /// </summary>
        public static string ReportTypeDigital {
            get {
                return ResourceManager.GetString("ReportTypeDigital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drugs.
        /// </summary>
        public static string ReportTypeDrugs {
            get {
                return ResourceManager.GetString("ReportTypeDrugs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand.
        /// </summary>
        public static string ReportTypeFire {
            get {
                return ResourceManager.GetString("ReportTypeFire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intimidatie.
        /// </summary>
        public static string ReportTypeIntimidation {
            get {
                return ResourceManager.GetString("ReportTypeIntimidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overlast.
        /// </summary>
        public static string ReportTypeNuisance {
            get {
                return ResourceManager.GetString("ReportTypeNuisance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diefstal.
        /// </summary>
        public static string ReportTypeTheft {
            get {
                return ResourceManager.GetString("ReportTypeTheft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voortuigen.
        /// </summary>
        public static string ReportTypeVehicles {
            get {
                return ResourceManager.GetString("ReportTypeVehicles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Agent.
        /// </summary>
        public static string ReportUserAgent {
            get {
                return ResourceManager.GetString("ReportUserAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lopende.
        /// </summary>
        public static string StatusInProgress {
            get {
                return ResourceManager.GetString("StatusInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string StatusOpen {
            get {
                return ResourceManager.GetString("StatusOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opgelost.
        /// </summary>
        public static string StatusSolved {
            get {
                return ResourceManager.GetString("StatusSolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overgedragen.
        /// </summary>
        public static string StatusTransferred {
            get {
                return ResourceManager.GetString("StatusTransferred", resourceCulture);
            }
        }
    }
}
