//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DisplayNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DisplayNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.DisplayNames", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacten.
        /// </summary>
        internal static string ReportContacts {
            get {
                return ResourceManager.GetString("ReportContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aangemaakt.
        /// </summary>
        internal static string ReportCreated {
            get {
                return ResourceManager.GetString("ReportCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beschrijving.
        /// </summary>
        internal static string ReportDescription {
            get {
                return ResourceManager.GetString("ReportDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ip.
        /// </summary>
        internal static string ReportIp {
            get {
                return ResourceManager.GetString("ReportIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locatie.
        /// </summary>
        internal static string ReportLocation {
            get {
                return ResourceManager.GetString("ReportLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum incident.
        /// </summary>
        internal static string ReportTime {
            get {
                return ResourceManager.GetString("ReportTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string ReportType {
            get {
                return ResourceManager.GetString("ReportType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Agent.
        /// </summary>
        internal static string ReportUserAgent {
            get {
                return ResourceManager.GetString("ReportUserAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lopende.
        /// </summary>
        internal static string StatusInProgress {
            get {
                return ResourceManager.GetString("StatusInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string StatusOpen {
            get {
                return ResourceManager.GetString("StatusOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opgelost.
        /// </summary>
        internal static string StatusSolved {
            get {
                return ResourceManager.GetString("StatusSolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overgedragen.
        /// </summary>
        internal static string StatusTransferred {
            get {
                return ResourceManager.GetString("StatusTransferred", resourceCulture);
            }
        }
    }
}
