//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 02/10/2014 10:14:10
namespace Lisa.Kiwi.WebApi.Access.KiwiService
{
    
    /// <summary>
    /// There are no comments for Container in the schema.
    /// </summary>
    public partial class Container : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new Container object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Container(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::System.Data.Services.Common.DataServiceProtocolVersion.V3)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "Lisa.Kiwi.WebApi.Models", "Lisa.Kiwi.WebApi.Access.KiwiService");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            resolvedType = this.DefaultResolveType(typeName, "Lisa.Kiwi.Data.Models", "Lisa.Kiwi.WebApi.Access.KiwiService.Lisa.Kiwi.Data.Models");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("Lisa.Kiwi.WebApi.Access.KiwiService.Lisa.Kiwi.Data.Models", global::System.StringComparison.Ordinal))
            {
                return string.Concat("Lisa.Kiwi.Data.Models.", clientType.Name);
            }
            if (clientType.Namespace.Equals("Lisa.Kiwi.WebApi.Access.KiwiService", global::System.StringComparison.Ordinal))
            {
                return string.Concat("Lisa.Kiwi.WebApi.Models.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for Report in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Report> Report
        {
            get
            {
                if ((this._Report == null))
                {
                    this._Report = base.CreateQuery<Report>("Report");
                }
                return this._Report;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Report> _Report;
        /// <summary>
        /// There are no comments for Contact in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Lisa.Kiwi.Data.Models.Contact> Contact
        {
            get
            {
                if ((this._Contact == null))
                {
                    this._Contact = base.CreateQuery<Lisa.Kiwi.Data.Models.Contact>("Contact");
                }
                return this._Contact;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Lisa.Kiwi.Data.Models.Contact> _Contact;
        /// <summary>
        /// There are no comments for Remark in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Lisa.Kiwi.Data.Models.Remark> Remark
        {
            get
            {
                if ((this._Remark == null))
                {
                    this._Remark = base.CreateQuery<Lisa.Kiwi.Data.Models.Remark>("Remark");
                }
                return this._Remark;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Lisa.Kiwi.Data.Models.Remark> _Remark;
        /// <summary>
        /// There are no comments for Status in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Lisa.Kiwi.Data.Models.Status> Status
        {
            get
            {
                if ((this._Status == null))
                {
                    this._Status = base.CreateQuery<Lisa.Kiwi.Data.Models.Status>("Status");
                }
                return this._Status;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Lisa.Kiwi.Data.Models.Status> _Status;
        /// <summary>
        /// There are no comments for Report in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToReport(Report report)
        {
            base.AddObject("Report", report);
        }
        /// <summary>
        /// There are no comments for Contact in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToContact(Lisa.Kiwi.Data.Models.Contact contact)
        {
            base.AddObject("Contact", contact);
        }
        /// <summary>
        /// There are no comments for Remark in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToRemark(Lisa.Kiwi.Data.Models.Remark remark)
        {
            base.AddObject("Remark", remark);
        }
        /// <summary>
        /// There are no comments for Status in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToStatus(Lisa.Kiwi.Data.Models.Status status)
        {
            base.AddObject("Status", status);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelPart0 = "<edmx:Edmx Version=\"1.0\" xmlns:edmx=\"http://schemas.microsoft.com/ado/2007/06/edm" +
                "x\"><edmx:DataServices m:DataServiceVersion=\"3.0\" m:MaxDataServiceVersion=\"3.0\" x" +
                "mlns:m=\"http://schemas.microsoft.com/ado/2007/08/dataservices/metadata\"><Schema " +
                "Namespace=\"Lisa.Kiwi.WebApi.Models\" xmlns=\"http://schemas.microsoft.com/ado/2009" +
                "/11/edm\"><EntityType Name=\"Report\"><Key><PropertyRef Name=\"Id\" /></Key><Property" +
                " Name=\"Id\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"Description\" Type" +
                "=\"Edm.String\" /><Property Name=\"Created\" Type=\"Edm.DateTime\" Nullable=\"false\" />" +
                "<Property Name=\"Location\" Type=\"Edm.String\" /><Property Name=\"Time\" Type=\"Edm.Da" +
                "teTime\" Nullable=\"false\" /><Property Name=\"Guid\" Type=\"Edm.String\" /><Property N" +
                "ame=\"UserAgent\" Type=\"Edm.String\" /><Property Name=\"Ip\" Type=\"Edm.String\" /><Pro" +
                "perty Name=\"Status\" Type=\"Edm.String\" Nullable=\"false\" /></EntityType></Schema><" +
                "Schema Namespace=\"Lisa.Kiwi.Data.Models\" xmlns=\"http://schemas.microsoft.com/ado" +
                "/2009/11/edm\"><EntityType Name=\"Contact\"><Key><PropertyRef Name=\"Id\" /></Key><Pr" +
                "operty Name=\"Id\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"Name\" Type=" +
                "\"Edm.String\" /><Property Name=\"PhoneNumber\" Type=\"Edm.String\" /><Property Name=\"" +
                "EmailAddress\" Type=\"Edm.String\" /><Property Name=\"StudentNumber\" Type=\"Edm.Int32" +
                "\" /></EntityType><EntityType Name=\"Remark\"><Key><PropertyRef Name=\"Id\" /></Key><" +
                "Property Name=\"Id\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"Created\" " +
                "Type=\"Edm.DateTime\" Nullable=\"false\" /><Property Name=\"Description\" Type=\"Edm.St" +
                "ring\" /><NavigationProperty Name=\"Report\" Relationship=\"Lisa.Kiwi.Data.Models.Li" +
                "sa_Kiwi_Data_Models_Remark_Report_Lisa_Kiwi_Data_Models_Report_ReportPartner\" To" +
                "Role=\"Report\" FromRole=\"ReportPartner\" /></EntityType><EntityType Name=\"Status\">" +
                "<Key><PropertyRef Name=\"Id\" /></Key><Property Name=\"Id\" Type=\"Edm.Int32\" Nullabl" +
                "e=\"false\" /><Property Name=\"Created\" Type=\"Edm.DateTime\" Nullable=\"false\" /><Pro" +
                "perty Name=\"Name\" Type=\"Edm.String\" Nullable=\"false\" /><NavigationProperty Name=" +
                "\"Report\" Relationship=\"Lisa.Kiwi.Data.Models.Lisa_Kiwi_Data_Models_Status_Report" +
                "_Lisa_Kiwi_Data_Models_Report_ReportPartner\" ToRole=\"Report\" FromRole=\"ReportPar" +
                "tner\" /></EntityType><EntityType Name=\"Report\"><Key><PropertyRef Name=\"Id\" /></K" +
                "ey><Property Name=\"Id\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"Descr" +
                "iption\" Type=\"Edm.String\" /><Property Name=\"Created\" Type=\"Edm.DateTime\" Nullabl" +
                "e=\"false\" /><Property Name=\"Location\" Type=\"Edm.String\" /><Property Name=\"Time\" " +
                "Type=\"Edm.DateTime\" Nullable=\"false\" /><Property Name=\"Guid\" Type=\"Edm.String\" /" +
                "><Property Name=\"UserAgent\" Type=\"Edm.String\" /><Property Name=\"Ip\" Type=\"Edm.St" +
                "ring\" /><Property Name=\"Type\" Type=\"Edm.String\" Nullable=\"false\" /><NavigationPr" +
                "operty Name=\"Contacts\" Relationship=\"Lisa.Kiwi.Data.Models.Lisa_Kiwi_Data_Models" +
                "_Report_Contacts_Lisa_Kiwi_Data_Models_Contact_ContactsPartner\" ToRole=\"Contacts" +
                "\" FromRole=\"ContactsPartner\" /></EntityType><Association Name=\"Lisa_Kiwi_Data_Mo" +
                "dels_Remark_Report_Lisa_Kiwi_Data_Models_Report_ReportPartner\"><End Type=\"Lisa.K" +
                "iwi.Data.Models.Report\" Role=\"Report\" Multiplicity=\"0..1\" /><End Type=\"Lisa.Kiwi" +
                ".Data.Models.Remark\" Role=\"ReportPartner\" Multiplicity=\"0..1\" /></Association><A" +
                "ssociation Name=\"Lisa_Kiwi_Data_Models_Status_Report_Lisa_Kiwi_Data_Models_Repor" +
                "t_ReportPartner\"><End Type=\"Lisa.Kiwi.Data.Models.Report\" Role=\"Report\" Multipli" +
                "city=\"0..1\" /><End Type=\"Lisa.Kiwi.Data.Models.Status\" Role=\"ReportPartner\" Mult" +
                "iplicity=\"0..1\" /></Association><Association Name=\"Lisa_Kiwi_Data_Models_Report_" +
                "Contacts_Lisa_Kiwi_Data_Models_Contact_ContactsPartner\"><End Type=\"Lisa.Kiwi.Dat" +
                "a.Models.Contact\" Role=\"Contacts\" Multiplicity=\"*\" /><End Type=\"Lisa.Kiwi.Data.M" +
                "odels.Report\" Role=\"ContactsPartner\" Multiplicity=\"0..1\" /></Association></Schem" +
                "a><Schema Namespace=\"Default\" xmlns=\"http://schemas.microsoft.com/ado/2009/11/ed" +
                "m\"><EntityContainer Name=\"Container\" m:IsDefaultEntityContainer=\"true\"><EntitySe" +
                "t Name=\"Report\" EntityType=\"Lisa.Kiwi.WebApi.Models.Report\" /><EntitySet Name=\"C" +
                "ontact\" EntityType=\"Lisa.Kiwi.Data.Models.Contact\" /><EntitySet Name=\"Remark\" En" +
                "tityType=\"Lisa.Kiwi.Data.Models.Remark\" /><EntitySet Name=\"Status\" EntityType=\"L" +
                "isa.Kiwi.Data.Models.Status\" /></EntityContainer></Schema></edmx:DataServices></" +
                "edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static string GetConcatenatedEdmxString()
            {
                return string.Concat(ModelPart0);
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            public static global::Microsoft.Data.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel LoadModelFromString()
            {
                string edmxToParse = GetConcatenatedEdmxString();
                global::System.Xml.XmlReader reader = CreateXmlReader(edmxToParse);
                try
                {
                    return global::Microsoft.Data.Edm.Csdl.EdmxReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
    /// <summary>
    /// There are no comments for Lisa.Kiwi.WebApi.Models.Report in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Report")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Report : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Report object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="created">Initial value of Created.</param>
        /// <param name="time">Initial value of Time.</param>
        /// <param name="status">Initial value of Status.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Report CreateReport(int ID, global::System.DateTime created, global::System.DateTime time, string status)
        {
            Report report = new Report();
            report.Id = ID;
            report.Created = created;
            report.Time = time;
            report.Status = status;
            return report;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this._Description = value;
                this.OnDescriptionChanged();
                this.OnPropertyChanged("Description");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Property Created in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime Created
        {
            get
            {
                return this._Created;
            }
            set
            {
                this.OnCreatedChanging(value);
                this._Created = value;
                this.OnCreatedChanged();
                this.OnPropertyChanged("Created");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _Created;
        partial void OnCreatedChanging(global::System.DateTime value);
        partial void OnCreatedChanged();
        /// <summary>
        /// There are no comments for Property Location in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Location
        {
            get
            {
                return this._Location;
            }
            set
            {
                this.OnLocationChanging(value);
                this._Location = value;
                this.OnLocationChanged();
                this.OnPropertyChanged("Location");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Location;
        partial void OnLocationChanging(string value);
        partial void OnLocationChanged();
        /// <summary>
        /// There are no comments for Property Time in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime Time
        {
            get
            {
                return this._Time;
            }
            set
            {
                this.OnTimeChanging(value);
                this._Time = value;
                this.OnTimeChanged();
                this.OnPropertyChanged("Time");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _Time;
        partial void OnTimeChanging(global::System.DateTime value);
        partial void OnTimeChanged();
        /// <summary>
        /// There are no comments for Property Guid in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Guid
        {
            get
            {
                return this._Guid;
            }
            set
            {
                this.OnGuidChanging(value);
                this._Guid = value;
                this.OnGuidChanged();
                this.OnPropertyChanged("Guid");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Guid;
        partial void OnGuidChanging(string value);
        partial void OnGuidChanged();
        /// <summary>
        /// There are no comments for Property UserAgent in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string UserAgent
        {
            get
            {
                return this._UserAgent;
            }
            set
            {
                this.OnUserAgentChanging(value);
                this._UserAgent = value;
                this.OnUserAgentChanged();
                this.OnPropertyChanged("UserAgent");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _UserAgent;
        partial void OnUserAgentChanging(string value);
        partial void OnUserAgentChanged();
        /// <summary>
        /// There are no comments for Property Ip in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Ip
        {
            get
            {
                return this._Ip;
            }
            set
            {
                this.OnIpChanging(value);
                this._Ip = value;
                this.OnIpChanged();
                this.OnPropertyChanged("Ip");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Ip;
        partial void OnIpChanging(string value);
        partial void OnIpChanged();
        /// <summary>
        /// There are no comments for Property Status in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Status
        {
            get
            {
                return this._Status;
            }
            set
            {
                this.OnStatusChanging(value);
                this._Status = value;
                this.OnStatusChanged();
                this.OnPropertyChanged("Status");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Status;
        partial void OnStatusChanging(string value);
        partial void OnStatusChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
// Original file name:
// Generation date: 02/10/2014 10:14:10
namespace Lisa.Kiwi.Data.Models
{
    
    /// <summary>
    /// There are no comments for Lisa.Kiwi.Data.Models.Contact in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Contact")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Contact : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Contact object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Contact CreateContact(int ID)
        {
            Contact contact = new Contact();
            contact.Id = ID;
            return contact;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property PhoneNumber in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string PhoneNumber
        {
            get
            {
                return this._PhoneNumber;
            }
            set
            {
                this.OnPhoneNumberChanging(value);
                this._PhoneNumber = value;
                this.OnPhoneNumberChanged();
                this.OnPropertyChanged("PhoneNumber");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _PhoneNumber;
        partial void OnPhoneNumberChanging(string value);
        partial void OnPhoneNumberChanged();
        /// <summary>
        /// There are no comments for Property EmailAddress in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string EmailAddress
        {
            get
            {
                return this._EmailAddress;
            }
            set
            {
                this.OnEmailAddressChanging(value);
                this._EmailAddress = value;
                this.OnEmailAddressChanged();
                this.OnPropertyChanged("EmailAddress");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _EmailAddress;
        partial void OnEmailAddressChanging(string value);
        partial void OnEmailAddressChanged();
        /// <summary>
        /// There are no comments for Property StudentNumber in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> StudentNumber
        {
            get
            {
                return this._StudentNumber;
            }
            set
            {
                this.OnStudentNumberChanging(value);
                this._StudentNumber = value;
                this.OnStudentNumberChanged();
                this.OnPropertyChanged("StudentNumber");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _StudentNumber;
        partial void OnStudentNumberChanging(global::System.Nullable<int> value);
        partial void OnStudentNumberChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for Lisa.Kiwi.Data.Models.Remark in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Remark")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Remark : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Remark object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="created">Initial value of Created.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Remark CreateRemark(int ID, global::System.DateTime created)
        {
            Remark remark = new Remark();
            remark.Id = ID;
            remark.Created = created;
            return remark;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Created in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime Created
        {
            get
            {
                return this._Created;
            }
            set
            {
                this.OnCreatedChanging(value);
                this._Created = value;
                this.OnCreatedChanged();
                this.OnPropertyChanged("Created");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _Created;
        partial void OnCreatedChanging(global::System.DateTime value);
        partial void OnCreatedChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this._Description = value;
                this.OnDescriptionChanged();
                this.OnPropertyChanged("Description");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Report in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Report Report
        {
            get
            {
                return this._Report;
            }
            set
            {
                this._Report = value;
                this.OnPropertyChanged("Report");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Report _Report;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for Lisa.Kiwi.Data.Models.Status in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Status")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Status : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Status object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="created">Initial value of Created.</param>
        /// <param name="name">Initial value of Name.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Status CreateStatus(int ID, global::System.DateTime created, string name)
        {
            Status status = new Status();
            status.Id = ID;
            status.Created = created;
            status.Name = name;
            return status;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Created in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime Created
        {
            get
            {
                return this._Created;
            }
            set
            {
                this.OnCreatedChanging(value);
                this._Created = value;
                this.OnCreatedChanged();
                this.OnPropertyChanged("Created");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _Created;
        partial void OnCreatedChanging(global::System.DateTime value);
        partial void OnCreatedChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Report in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Report Report
        {
            get
            {
                return this._Report;
            }
            set
            {
                this._Report = value;
                this.OnPropertyChanged("Report");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Report _Report;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for Lisa.Kiwi.Data.Models.Report in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Report : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Report object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="created">Initial value of Created.</param>
        /// <param name="time">Initial value of Time.</param>
        /// <param name="type">Initial value of Type.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Report CreateReport(int ID, global::System.DateTime created, global::System.DateTime time, string type)
        {
            Report report = new Report();
            report.Id = ID;
            report.Created = created;
            report.Time = time;
            report.Type = type;
            return report;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this._Description = value;
                this.OnDescriptionChanged();
                this.OnPropertyChanged("Description");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Property Created in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime Created
        {
            get
            {
                return this._Created;
            }
            set
            {
                this.OnCreatedChanging(value);
                this._Created = value;
                this.OnCreatedChanged();
                this.OnPropertyChanged("Created");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _Created;
        partial void OnCreatedChanging(global::System.DateTime value);
        partial void OnCreatedChanged();
        /// <summary>
        /// There are no comments for Property Location in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Location
        {
            get
            {
                return this._Location;
            }
            set
            {
                this.OnLocationChanging(value);
                this._Location = value;
                this.OnLocationChanged();
                this.OnPropertyChanged("Location");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Location;
        partial void OnLocationChanging(string value);
        partial void OnLocationChanged();
        /// <summary>
        /// There are no comments for Property Time in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime Time
        {
            get
            {
                return this._Time;
            }
            set
            {
                this.OnTimeChanging(value);
                this._Time = value;
                this.OnTimeChanged();
                this.OnPropertyChanged("Time");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _Time;
        partial void OnTimeChanging(global::System.DateTime value);
        partial void OnTimeChanged();
        /// <summary>
        /// There are no comments for Property Guid in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Guid
        {
            get
            {
                return this._Guid;
            }
            set
            {
                this.OnGuidChanging(value);
                this._Guid = value;
                this.OnGuidChanged();
                this.OnPropertyChanged("Guid");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Guid;
        partial void OnGuidChanging(string value);
        partial void OnGuidChanged();
        /// <summary>
        /// There are no comments for Property UserAgent in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string UserAgent
        {
            get
            {
                return this._UserAgent;
            }
            set
            {
                this.OnUserAgentChanging(value);
                this._UserAgent = value;
                this.OnUserAgentChanged();
                this.OnPropertyChanged("UserAgent");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _UserAgent;
        partial void OnUserAgentChanging(string value);
        partial void OnUserAgentChanged();
        /// <summary>
        /// There are no comments for Property Ip in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Ip
        {
            get
            {
                return this._Ip;
            }
            set
            {
                this.OnIpChanging(value);
                this._Ip = value;
                this.OnIpChanged();
                this.OnPropertyChanged("Ip");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Ip;
        partial void OnIpChanging(string value);
        partial void OnIpChanged();
        /// <summary>
        /// There are no comments for Property Type in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Type
        {
            get
            {
                return this._Type;
            }
            set
            {
                this.OnTypeChanging(value);
                this._Type = value;
                this.OnTypeChanged();
                this.OnPropertyChanged("Type");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Type;
        partial void OnTypeChanging(string value);
        partial void OnTypeChanged();
        /// <summary>
        /// There are no comments for Contacts in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Contact> Contacts
        {
            get
            {
                return this._Contacts;
            }
            set
            {
                this._Contacts = value;
                this.OnPropertyChanged("Contacts");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Contact> _Contacts = new global::System.Data.Services.Client.DataServiceCollection<Contact>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
