//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DisplayNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DisplayNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.DisplayNames", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EHBO.
        /// </summary>
        internal static string Category_FirstAid {
            get {
                return ResourceManager.GetString("Category_FirstAid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mediacentrum.
        /// </summary>
        internal static string DrugsController_Details_Mediacentrum {
            get {
                return ResourceManager.GetString("DrugsController_Details_Mediacentrum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacten.
        /// </summary>
        internal static string ReportContacts {
            get {
                return ResourceManager.GetString("ReportContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appartementen.
        /// </summary>
        internal static string ReportController_Details_Appartementen {
            get {
                return ResourceManager.GetString("ReportController_Details_Appartementen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arcobaleno.
        /// </summary>
        internal static string ReportController_Details_Arcobaleno {
            get {
                return ResourceManager.GetString("ReportController_Details_Arcobaleno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azurro.
        /// </summary>
        internal static string ReportController_Details_Azurro {
            get {
                return ResourceManager.GetString("ReportController_Details_Azurro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Betaalde parkeerplaats.
        /// </summary>
        internal static string ReportController_Details_Betaalde_parkeerplaats {
            get {
                return ResourceManager.GetString("ReportController_Details_Betaalde_parkeerplaats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bianco.
        /// </summary>
        internal static string ReportController_Details_Bianco {
            get {
                return ResourceManager.GetString("ReportController_Details_Bianco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bogermanschool.
        /// </summary>
        internal static string ReportController_Details_Bogermanschool {
            get {
                return ResourceManager.GetString("ReportController_Details_Bogermanschool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brandweerkazerne.
        /// </summary>
        internal static string ReportController_Details_Brandweerkazerne {
            get {
                return ResourceManager.GetString("ReportController_Details_Brandweerkazerne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buiten (Openbare Weg).
        /// </summary>
        internal static string ReportController_Details_Buiten {
            get {
                return ResourceManager.GetString("ReportController_Details_Buiten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celeste.
        /// </summary>
        internal static string ReportController_Details_Celeste {
            get {
                return ResourceManager.GetString("ReportController_Details_Celeste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drechsteden College.
        /// </summary>
        internal static string ReportController_Details_Drechsteden_College {
            get {
                return ResourceManager.GetString("ReportController_Details_Drechsteden_College", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duurzaamheidsfabriek.
        /// </summary>
        internal static string ReportController_Details_Duurzaamheidsfabriek {
            get {
                return ResourceManager.GetString("ReportController_Details_Duurzaamheidsfabriek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eljakim.
        /// </summary>
        internal static string ReportController_Details_Eljakim {
            get {
                return ResourceManager.GetString("ReportController_Details_Eljakim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giallo.
        /// </summary>
        internal static string ReportController_Details_Giallo {
            get {
                return ResourceManager.GetString("ReportController_Details_Giallo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indaco.
        /// </summary>
        internal static string ReportController_Details_Indaco {
            get {
                return ResourceManager.GetString("ReportController_Details_Indaco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jubal.
        /// </summary>
        internal static string ReportController_Details_Jubal {
            get {
                return ResourceManager.GetString("ReportController_Details_Jubal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lilla.
        /// </summary>
        internal static string ReportController_Details_Lilla {
            get {
                return ResourceManager.GetString("ReportController_Details_Lilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marrone.
        /// </summary>
        internal static string ReportController_Details_Marrone {
            get {
                return ResourceManager.GetString("ReportController_Details_Marrone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orca.
        /// </summary>
        internal static string ReportController_Details_Orca {
            get {
                return ResourceManager.GetString("ReportController_Details_Orca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Romboutslaan.
        /// </summary>
        internal static string ReportController_Details_Romboutslaan {
            get {
                return ResourceManager.GetString("ReportController_Details_Romboutslaan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rosa.
        /// </summary>
        internal static string ReportController_Details_Rosa {
            get {
                return ResourceManager.GetString("ReportController_Details_Rosa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samenwerkingsgebouw.
        /// </summary>
        internal static string ReportController_Details_Samenwerkingsgebouw {
            get {
                return ResourceManager.GetString("ReportController_Details_Samenwerkingsgebouw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schippersinternaat.
        /// </summary>
        internal static string ReportController_Details_Schippersinternaat {
            get {
                return ResourceManager.GetString("ReportController_Details_Schippersinternaat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sporthal.
        /// </summary>
        internal static string ReportController_Details_Sporthal {
            get {
                return ResourceManager.GetString("ReportController_Details_Sporthal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syndion.
        /// </summary>
        internal static string ReportController_Details_Syndion {
            get {
                return ResourceManager.GetString("ReportController_Details_Syndion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tennisvereniging D.L.T.C.
        /// </summary>
        internal static string ReportController_Details_Tennisvereniging_D_L_T_C {
            get {
                return ResourceManager.GetString("ReportController_Details_Tennisvereniging_D_L_T_C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verde.
        /// </summary>
        internal static string ReportController_Details_Verde {
            get {
                return ResourceManager.GetString("ReportController_Details_Verde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Villa Volta.
        /// </summary>
        internal static string ReportController_Details_Villa_Volta {
            get {
                return ResourceManager.GetString("ReportController_Details_Villa_Volta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wartburg College.
        /// </summary>
        internal static string ReportController_Details_Wartburg_College {
            get {
                return ResourceManager.GetString("ReportController_Details_Wartburg_College", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aangemaakt.
        /// </summary>
        internal static string ReportCreated {
            get {
                return ResourceManager.GetString("ReportCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beschrijving.
        /// </summary>
        internal static string ReportDescription {
            get {
                return ResourceManager.GetString("ReportDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ip.
        /// </summary>
        internal static string ReportIp {
            get {
                return ResourceManager.GetString("ReportIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locatie.
        /// </summary>
        internal static string ReportLocation {
            get {
                return ResourceManager.GetString("ReportLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tijd.
        /// </summary>
        internal static string ReportTime {
            get {
                return ResourceManager.GetString("ReportTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string ReportType {
            get {
                return ResourceManager.GetString("ReportType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pesten.
        /// </summary>
        internal static string ReportTypeBullying {
            get {
                return ResourceManager.GetString("ReportTypeBullying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inbraak.
        /// </summary>
        internal static string ReportTypeBurglary {
            get {
                return ResourceManager.GetString("ReportTypeBurglary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vernieling.
        /// </summary>
        internal static string ReportTypeDestruction {
            get {
                return ResourceManager.GetString("ReportTypeDestruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digitaal.
        /// </summary>
        internal static string ReportTypeDigital {
            get {
                return ResourceManager.GetString("ReportTypeDigital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drugs.
        /// </summary>
        internal static string ReportTypeDrugs {
            get {
                return ResourceManager.GetString("ReportTypeDrugs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EHBO.
        /// </summary>
        internal static string ReportTypeEHBO {
            get {
                return ResourceManager.GetString("ReportTypeEHBO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vechtpartij.
        /// </summary>
        internal static string ReportTypeFighting {
            get {
                return ResourceManager.GetString("ReportTypeFighting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand.
        /// </summary>
        internal static string ReportTypeFire {
            get {
                return ResourceManager.GetString("ReportTypeFire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intimidatie.
        /// </summary>
        internal static string ReportTypeIntimidation {
            get {
                return ResourceManager.GetString("ReportTypeIntimidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overig.
        /// </summary>
        internal static string ReportTypeMisc {
            get {
                return ResourceManager.GetString("ReportTypeMisc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overlast.
        /// </summary>
        internal static string ReportTypeNuisance {
            get {
                return ResourceManager.GetString("ReportTypeNuisance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diefstal.
        /// </summary>
        internal static string ReportTypeTheft {
            get {
                return ResourceManager.GetString("ReportTypeTheft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voertuigen.
        /// </summary>
        internal static string ReportTypeVehicles {
            get {
                return ResourceManager.GetString("ReportTypeVehicles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Agent.
        /// </summary>
        internal static string ReportUserAgent {
            get {
                return ResourceManager.GetString("ReportUserAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lopende.
        /// </summary>
        internal static string StatusInProgress {
            get {
                return ResourceManager.GetString("StatusInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string StatusOpen {
            get {
                return ResourceManager.GetString("StatusOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opgelost.
        /// </summary>
        internal static string StatusSolved {
            get {
                return ResourceManager.GetString("StatusSolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overgedragen.
        /// </summary>
        internal static string StatusTransferred {
            get {
                return ResourceManager.GetString("StatusTransferred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tijd.
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
    }
}
