//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ReportProperties {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReportProperties() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ReportProperties", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het slachtoffer is:.
        /// </summary>
        internal static string BullyVictim {
            get {
                return ResourceManager.GetString("BullyVictim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tijd van overval:.
        /// </summary>
        internal static string DateOfTheft {
            get {
                return ResourceManager.GetString("DateOfTheft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verdere beschijving:.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het wordt verhandelt..
        /// </summary>
        internal static string DrugsDealing {
            get {
                return ResourceManager.GetString("DrugsDealing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het wordt gebruikt..
        /// </summary>
        internal static string DrugsUsing {
            get {
                return ResourceManager.GetString("DrugsUsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er waren zoveel mensen betrokken:.
        /// </summary>
        internal static string FightCount {
            get {
                return ResourceManager.GetString("FightCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is het slachtoffer bewusteloos?.
        /// </summary>
        internal static string IsUnconsious {
            get {
                return ResourceManager.GetString("IsUnconsious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestolen Voorwerp:.
        /// </summary>
        internal static string StolenObject {
            get {
                return ResourceManager.GetString("StolenObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nee.
        /// </summary>
        internal static string UnconsciousFalse {
            get {
                return ResourceManager.GetString("UnconsciousFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ja.
        /// </summary>
        internal static string UnconsciousTrue {
            get {
                return ResourceManager.GetString("UnconsciousTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word de drugs gebruikt of verhandeld:.
        /// </summary>
        internal static string UsingOrDealing {
            get {
                return ResourceManager.GetString("UsingOrDealing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hier is het wapen:.
        /// </summary>
        internal static string WeaponLocation {
            get {
                return ResourceManager.GetString("WeaponLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het betrokken wapen is een:.
        /// </summary>
        internal static string WeaponPresent {
            get {
                return ResourceManager.GetString("WeaponPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nee.
        /// </summary>
        internal static string WeaponPresentFalse {
            get {
                return ResourceManager.GetString("WeaponPresentFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ja.
        /// </summary>
        internal static string WeaponPresentTrue {
            get {
                return ResourceManager.GetString("WeaponPresentTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Om wat voor wapen is het:.
        /// </summary>
        internal static string WeaponType {
            get {
                return ResourceManager.GetString("WeaponType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hier is geen waarde voor ingevult..
        /// </summary>
        internal static string _null {
            get {
                return ResourceManager.GetString("_null", resourceCulture);
            }
        }
    }
}
