// <auto-generated />
namespace Lisa.Kiwi.WebApi
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Vehicles : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Vehicles));
        
        string IMigrationMetadata.Id
        {
            get { return "201510061236128_Vehicles"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
