//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lisa.Kiwi.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Buildings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Buildings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lisa.Kiwi.Web.Resources.Buildings", typeof(Buildings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appartementen.
        /// </summary>
        public static string Appartementen {
            get {
                return ResourceManager.GetString("Appartementen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in de.
        /// </summary>
        public static string Appartementen_Preposition {
            get {
                return ResourceManager.GetString("Appartementen_Preposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arcobaleno.
        /// </summary>
        public static string Arcobaleno {
            get {
                return ResourceManager.GetString("Arcobaleno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in.
        /// </summary>
        public static string Arcobaleno_Preposition {
            get {
                return ResourceManager.GetString("Arcobaleno_Preposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azzurro.
        /// </summary>
        public static string Azzurro {
            get {
                return ResourceManager.GetString("Azzurro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in.
        /// </summary>
        public static string Azzurro_Preposition {
            get {
                return ResourceManager.GetString("Azzurro_Preposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Betaalde Parkeerplaats.
        /// </summary>
        public static string BetaaldeParkeerplaats {
            get {
                return ResourceManager.GetString("BetaaldeParkeerplaats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to op de.
        /// </summary>
        public static string BetaaldeParkeerplaats_Preposition {
            get {
                return ResourceManager.GetString("BetaaldeParkeerplaats_Preposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bianco.
        /// </summary>
        public static string Bianco {
            get {
                return ResourceManager.GetString("Bianco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in.
        /// </summary>
        public static string Bianco_Preposition {
            get {
                return ResourceManager.GetString("Bianco_Preposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bogermanschool.
        /// </summary>
        public static string Bogermanschool {
            get {
                return ResourceManager.GetString("Bogermanschool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in de.
        /// </summary>
        public static string Bogermanschool_Preposition {
            get {
                return ResourceManager.GetString("Bogermanschool_Preposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brandweerkazerne.
        /// </summary>
        public static string Brandweerkazerne {
            get {
                return ResourceManager.GetString("Brandweerkazerne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in de.
        /// </summary>
        public static string Brandweerkazerne_Preposition {
            get {
                return ResourceManager.GetString("Brandweerkazerne_Preposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Openbare weg.
        /// </summary>
        public static string Buiten {
            get {
                return ResourceManager.GetString("Buiten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to op de.
        /// </summary>
        public static string Buiten_Preposition {
            get {
                return ResourceManager.GetString("Buiten_Preposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celeste.
        /// </summary>
        public static string Celeste {
            get {
                return ResourceManager.GetString("Celeste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in.
        /// </summary>
        public static string Celeste_Preposition {
            get {
                return ResourceManager.GetString("Celeste_Preposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drechtstedencollege.
        /// </summary>
        public static string Drechtstedencollege {
            get {
                return ResourceManager.GetString("Drechtstedencollege", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in het.
        /// </summary>
        public static string Drechtstedencollege_Preposition {
            get {
                return ResourceManager.GetString("Drechtstedencollege_Preposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duurzaamheidsfabriek.
        /// </summary>
        public static string Duurzaamheidsfabriek {
            get {
                return ResourceManager.GetString("Duurzaamheidsfabriek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in de.
        /// </summary>
        public static string Duurzaamheidsfabriek_Preposition {
            get {
                return ResourceManager.GetString("Duurzaamheidsfabriek_Preposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giallo.
        /// </summary>
        public static string Giallo {
            get {
                return ResourceManager.GetString("Giallo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in.
        /// </summary>
        public static string Giallo_Preposition {
            get {
                return ResourceManager.GetString("Giallo_Preposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grand Café Bellissimo.
        /// </summary>
        public static string GrandCafe {
            get {
                return ResourceManager.GetString("GrandCafe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in het.
        /// </summary>
        public static string GrandCafe_Preposition {
            get {
                return ResourceManager.GetString("GrandCafe_Preposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grote parkeerplaats.
        /// </summary>
        public static string GroteParkeerplaats {
            get {
                return ResourceManager.GetString("GroteParkeerplaats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to op de.
        /// </summary>
        public static string GroteParkeerplaats_Preposition {
            get {
                return ResourceManager.GetString("GroteParkeerplaats_Preposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indaco.
        /// </summary>
        public static string Indaco {
            get {
                return ResourceManager.GetString("Indaco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in.
        /// </summary>
        public static string Indaco_Preposition {
            get {
                return ResourceManager.GetString("Indaco_Preposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klimhal.
        /// </summary>
        public static string Klimhal {
            get {
                return ResourceManager.GetString("Klimhal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in de.
        /// </summary>
        public static string Klimhal_Preposition {
            get {
                return ResourceManager.GetString("Klimhal_Preposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lilla.
        /// </summary>
        public static string Lilla {
            get {
                return ResourceManager.GetString("Lilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in.
        /// </summary>
        public static string Lilla_Preposition {
            get {
                return ResourceManager.GetString("Lilla_Preposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marrone.
        /// </summary>
        public static string Marrone {
            get {
                return ResourceManager.GetString("Marrone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in.
        /// </summary>
        public static string Marrone_Preposition {
            get {
                return ResourceManager.GetString("Marrone_Preposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Da Vinci Media.
        /// </summary>
        public static string Media {
            get {
                return ResourceManager.GetString("Media", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in.
        /// </summary>
        public static string Media_Preposition {
            get {
                return ResourceManager.GetString("Media_Preposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocra.
        /// </summary>
        public static string Ocra {
            get {
                return ResourceManager.GetString("Ocra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in.
        /// </summary>
        public static string Ocra_Preposition {
            get {
                return ResourceManager.GetString("Ocra_Preposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orthodontist.
        /// </summary>
        public static string Orthodontist {
            get {
                return ResourceManager.GetString("Orthodontist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bij de.
        /// </summary>
        public static string Orthodontist_Preposition {
            get {
                return ResourceManager.GetString("Orthodontist_Preposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Betaalde parkeerplaats.
        /// </summary>
        public static string Parkeerplaats {
            get {
                return ResourceManager.GetString("Parkeerplaats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to op de.
        /// </summary>
        public static string Parkeerplaats_Preposition {
            get {
                return ResourceManager.GetString("Parkeerplaats_Preposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parkeerplaats brandweerkazerne.
        /// </summary>
        public static string ParkeerplaatsBrandweerkazerne {
            get {
                return ResourceManager.GetString("ParkeerplaatsBrandweerkazerne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to op de.
        /// </summary>
        public static string ParkeerplaatsBrandweerkazerne__Preposition {
            get {
                return ResourceManager.GetString("ParkeerplaatsBrandweerkazerne__Preposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parkeerplaats Duurzaamheidsfabriek.
        /// </summary>
        public static string ParkeerplaatsDuurzaamheidsfabriek {
            get {
                return ResourceManager.GetString("ParkeerplaatsDuurzaamheidsfabriek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Romboutslaan 40.
        /// </summary>
        public static string Romboutslaan {
            get {
                return ResourceManager.GetString("Romboutslaan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in de.
        /// </summary>
        public static string Romboutslaan_Preposition {
            get {
                return ResourceManager.GetString("Romboutslaan_Preposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rosa.
        /// </summary>
        public static string Rosa {
            get {
                return ResourceManager.GetString("Rosa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in.
        /// </summary>
        public static string Rosa_Preposition {
            get {
                return ResourceManager.GetString("Rosa_Preposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samenwerkingsgebouw.
        /// </summary>
        public static string Samenwerkingsgebouw {
            get {
                return ResourceManager.GetString("Samenwerkingsgebouw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in het.
        /// </summary>
        public static string Samenwerkingsgebouw_Preposition {
            get {
                return ResourceManager.GetString("Samenwerkingsgebouw_Preposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schippersinternaat.
        /// </summary>
        public static string Schippersinternaat {
            get {
                return ResourceManager.GetString("Schippersinternaat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in het.
        /// </summary>
        public static string Schippersinternaat_Preposition {
            get {
                return ResourceManager.GetString("Schippersinternaat_Preposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sporthal.
        /// </summary>
        public static string Sporthal {
            get {
                return ResourceManager.GetString("Sporthal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in de.
        /// </summary>
        public static string Sporthal_Preposition {
            get {
                return ResourceManager.GetString("Sporthal_Preposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veiligheidsregio.
        /// </summary>
        public static string Veiligheidsregio {
            get {
                return ResourceManager.GetString("Veiligheidsregio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in de.
        /// </summary>
        public static string Veiligheidsregio_Preposition {
            get {
                return ResourceManager.GetString("Veiligheidsregio_Preposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verde.
        /// </summary>
        public static string Verde {
            get {
                return ResourceManager.GetString("Verde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in.
        /// </summary>
        public static string Verde_Preposition {
            get {
                return ResourceManager.GetString("Verde_Preposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wartburg College.
        /// </summary>
        public static string Wartburg {
            get {
                return ResourceManager.GetString("Wartburg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in het.
        /// </summary>
        public static string Wartburg_Preposition {
            get {
                return ResourceManager.GetString("Wartburg_Preposition", resourceCulture);
            }
        }
    }
}
