//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Buildings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Buildings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lisa.Kiwi.Web.Resources.Buildings", typeof(Buildings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appartementen.
        /// </summary>
        public static string Appartementen {
            get {
                return ResourceManager.GetString("Appartementen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DVC Arcobaleno.
        /// </summary>
        public static string Arcobaleno {
            get {
                return ResourceManager.GetString("Arcobaleno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DVC Azzurro.
        /// </summary>
        public static string Azzurro {
            get {
                return ResourceManager.GetString("Azzurro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DVC Bianco.
        /// </summary>
        public static string Bianco {
            get {
                return ResourceManager.GetString("Bianco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ds. Bogermanschool.
        /// </summary>
        public static string Bogermanschool {
            get {
                return ResourceManager.GetString("Bogermanschool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brandweerkazerne.
        /// </summary>
        public static string Brandweerkazerne {
            get {
                return ResourceManager.GetString("Brandweerkazerne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buiten (Openbare Weg).
        /// </summary>
        public static string Buiten {
            get {
                return ResourceManager.GetString("Buiten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DVC Celeste.
        /// </summary>
        public static string Celeste {
            get {
                return ResourceManager.GetString("Celeste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drechtsteden college.
        /// </summary>
        public static string Drechtstedencollege {
            get {
                return ResourceManager.GetString("Drechtstedencollege", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duurzaamheidsfabriek.
        /// </summary>
        public static string Duurzaamheidsfabriek {
            get {
                return ResourceManager.GetString("Duurzaamheidsfabriek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DVC Giallo.
        /// </summary>
        public static string Giallo {
            get {
                return ResourceManager.GetString("Giallo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DVC Indaco.
        /// </summary>
        public static string Indaco {
            get {
                return ResourceManager.GetString("Indaco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klimhal.
        /// </summary>
        public static string Klimhal {
            get {
                return ResourceManager.GetString("Klimhal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DVC Lilla.
        /// </summary>
        public static string Lilla {
            get {
                return ResourceManager.GetString("Lilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DVC Marrone.
        /// </summary>
        public static string Marrone {
            get {
                return ResourceManager.GetString("Marrone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DVC media.
        /// </summary>
        public static string media {
            get {
                return ResourceManager.GetString("media", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DVC Ocra.
        /// </summary>
        public static string Ocra {
            get {
                return ResourceManager.GetString("Ocra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orthodontist.
        /// </summary>
        public static string Orthodontist {
            get {
                return ResourceManager.GetString("Orthodontist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Betaalde parkeerplaats.
        /// </summary>
        public static string Parkeerplaats {
            get {
                return ResourceManager.GetString("Parkeerplaats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parkeerplaats Brandweerkazerne.
        /// </summary>
        public static string ParkeerplaatsBrandweerkazerne {
            get {
                return ResourceManager.GetString("ParkeerplaatsBrandweerkazerne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parkeerplaats Duurzaamheidsfabriek.
        /// </summary>
        public static string ParkeerplaatsDuurzaamheidsfabriek {
            get {
                return ResourceManager.GetString("ParkeerplaatsDuurzaamheidsfabriek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parkeerplaats Ocra.
        /// </summary>
        public static string ParkeerplaatsOcra {
            get {
                return ResourceManager.GetString("ParkeerplaatsOcra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DVC Romboutslaan 40.
        /// </summary>
        public static string Romboutslaan {
            get {
                return ResourceManager.GetString("Romboutslaan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DVC Rosa.
        /// </summary>
        public static string Rosa {
            get {
                return ResourceManager.GetString("Rosa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samenwerkingsgebouw.
        /// </summary>
        public static string Samenwerkingsgebouw {
            get {
                return ResourceManager.GetString("Samenwerkingsgebouw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schippersinternaat.
        /// </summary>
        public static string Schippersinternaat {
            get {
                return ResourceManager.GetString("Schippersinternaat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sporthal.
        /// </summary>
        public static string Sporthal {
            get {
                return ResourceManager.GetString("Sporthal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veiligheidsregio.
        /// </summary>
        public static string Veiligheidsregio {
            get {
                return ResourceManager.GetString("Veiligheidsregio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DVC Verde.
        /// </summary>
        public static string Verde {
            get {
                return ResourceManager.GetString("Verde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wartburg college.
        /// </summary>
        public static string Wartburg {
            get {
                return ResourceManager.GetString("Wartburg", resourceCulture);
            }
        }
    }
}
