//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DisplayNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DisplayNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lisa.Kiwi.Web.Resources.DisplayNames", typeof(DisplayNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EHBO.
        /// </summary>
        public static string Category_FirstAid {
            get {
                return ResourceManager.GetString("Category_FirstAid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contactgegevens verplicht.
        /// </summary>
        public static string ContactRequired {
            get {
                return ResourceManager.GetString("ContactRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mediacentrum.
        /// </summary>
        public static string DrugsController_Details_Mediacentrum {
            get {
                return ResourceManager.GetString("DrugsController_Details_Mediacentrum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mailadres.
        /// </summary>
        public static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inloggen.
        /// </summary>
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naam.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieuw wachtwoord.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wachtwoord.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Betrokkene.
        /// </summary>
        public static string PersonInvolved {
            get {
                return ResourceManager.GetString("PersonInvolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefoonnummer.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieuwe wachtwoord herhalen.
        /// </summary>
        public static string RepeatNewPassword {
            get {
                return ResourceManager.GetString("RepeatNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacten.
        /// </summary>
        public static string ReportContacts {
            get {
                return ResourceManager.GetString("ReportContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aangemaakt.
        /// </summary>
        public static string ReportCreated {
            get {
                return ResourceManager.GetString("ReportCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beschrijving.
        /// </summary>
        public static string ReportDescription {
            get {
                return ResourceManager.GetString("ReportDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ip.
        /// </summary>
        public static string ReportIp {
            get {
                return ResourceManager.GetString("ReportIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locatie.
        /// </summary>
        public static string ReportLocation {
            get {
                return ResourceManager.GetString("ReportLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tijd.
        /// </summary>
        public static string ReportTime {
            get {
                return ResourceManager.GetString("ReportTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string ReportType {
            get {
                return ResourceManager.GetString("ReportType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pesten.
        /// </summary>
        public static string ReportTypeBullying {
            get {
                return ResourceManager.GetString("ReportTypeBullying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inbraak.
        /// </summary>
        public static string ReportTypeBurglary {
            get {
                return ResourceManager.GetString("ReportTypeBurglary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vernieling.
        /// </summary>
        public static string ReportTypeDestruction {
            get {
                return ResourceManager.GetString("ReportTypeDestruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digitaal.
        /// </summary>
        public static string ReportTypeDigital {
            get {
                return ResourceManager.GetString("ReportTypeDigital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drugs.
        /// </summary>
        public static string ReportTypeDrugs {
            get {
                return ResourceManager.GetString("ReportTypeDrugs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EHBO.
        /// </summary>
        public static string ReportTypeEHBO {
            get {
                return ResourceManager.GetString("ReportTypeEHBO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vechtpartij.
        /// </summary>
        public static string ReportTypeFighting {
            get {
                return ResourceManager.GetString("ReportTypeFighting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand.
        /// </summary>
        public static string ReportTypeFire {
            get {
                return ResourceManager.GetString("ReportTypeFire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intimidatie.
        /// </summary>
        public static string ReportTypeIntimidation {
            get {
                return ResourceManager.GetString("ReportTypeIntimidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overig.
        /// </summary>
        public static string ReportTypeMisc {
            get {
                return ResourceManager.GetString("ReportTypeMisc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overlast.
        /// </summary>
        public static string ReportTypeNuisance {
            get {
                return ResourceManager.GetString("ReportTypeNuisance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diefstal.
        /// </summary>
        public static string ReportTypeTheft {
            get {
                return ResourceManager.GetString("ReportTypeTheft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voertuigen.
        /// </summary>
        public static string ReportTypeVehicles {
            get {
                return ResourceManager.GetString("ReportTypeVehicles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Agent.
        /// </summary>
        public static string ReportUserAgent {
            get {
                return ResourceManager.GetString("ReportUserAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounttype.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lopende.
        /// </summary>
        public static string StatusInProgress {
            get {
                return ResourceManager.GetString("StatusInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string StatusOpen {
            get {
                return ResourceManager.GetString("StatusOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opgelost.
        /// </summary>
        public static string StatusSolved {
            get {
                return ResourceManager.GetString("StatusSolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overgedragen.
        /// </summary>
        public static string StatusTransferred {
            get {
                return ResourceManager.GetString("StatusTransferred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tijd.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gebruikersnaam.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slachtoffer.
        /// </summary>
        public static string Victim {
            get {
                return ResourceManager.GetString("Victim", resourceCulture);
            }
        }
    }
}
