//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DisplayNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DisplayNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lisa.Kiwi.Web.Resources.DisplayNames", typeof(DisplayNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wat kun je er verder over vertellen?.
        /// </summary>
        public static string BullyingDescription {
            get {
                return ResourceManager.GetString("BullyingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EHBO.
        /// </summary>
        public static string Category_FirstAid {
            get {
                return ResourceManager.GetString("Category_FirstAid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contactgegevens.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wat is uw e-mailadres?.
        /// </summary>
        public static string ContactEmail {
            get {
                return ResourceManager.GetString("ContactEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wat is uw naam?.
        /// </summary>
        public static string ContactName {
            get {
                return ResourceManager.GetString("ContactName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wat is uw telefoonnummer?.
        /// </summary>
        public static string ContactPhoneNumber {
            get {
                return ResourceManager.GetString("ContactPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contactgegevens verplicht.
        /// </summary>
        public static string ContactRequired {
            get {
                return ResourceManager.GetString("ContactRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mogen we contact met u opnemen?.
        /// </summary>
        public static string ContactTitle {
            get {
                return ResourceManager.GetString("ContactTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wanneer is het gestolen?.
        /// </summary>
        public static string DateOfTheft {
            get {
                return ResourceManager.GetString("DateOfTheft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wat kun je er verder over vertellen?.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wat heb je gezien?.
        /// </summary>
        public static string DrugsAction {
            get {
                return ResourceManager.GetString("DrugsAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mediacentrum.
        /// </summary>
        public static string DrugsController_Details_Mediacentrum {
            get {
                return ResourceManager.GetString("DrugsController_Details_Mediacentrum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mailadres.
        /// </summary>
        public static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoeveel personen zijn er aan het vechten?.
        /// </summary>
        public static string FightCount {
            get {
                return ResourceManager.GetString("FightCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heb je een wapen gezien?.
        /// </summary>
        public static string FightWeapon {
            get {
                return ResourceManager.GetString("FightWeapon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wat wilt u melden?.
        /// </summary>
        public static string Index {
            get {
                return ResourceManager.GetString("Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inloggen.
        /// </summary>
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naam.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieuw wachtwoord.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wachtwoord.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wie heb je gezien?.
        /// </summary>
        public static string Perpetrator {
            get {
                return ResourceManager.GetString("Perpetrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoe oud is de persoon?.
        /// </summary>
        public static string PerpetratorAge {
            get {
                return ResourceManager.GetString("PerpetratorAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wat voor kleding draagt de persoon?.
        /// </summary>
        public static string PerpetratorClothing {
            get {
                return ResourceManager.GetString("PerpetratorClothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoe heet de persoon?.
        /// </summary>
        public static string PerpetratorName {
            get {
                return ResourceManager.GetString("PerpetratorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heeft de persoon nog andere opvallende kenmerken?.
        /// </summary>
        public static string PerpetratorProperties {
            get {
                return ResourceManager.GetString("PerpetratorProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wat is het geslacht van de persoon?.
        /// </summary>
        public static string PerpetratorSex {
            get {
                return ResourceManager.GetString("PerpetratorSex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welke huidskleur heeft de persoon?.
        /// </summary>
        public static string PerpetratorSkinColor {
            get {
                return ResourceManager.GetString("PerpetratorSkinColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Betrokkene.
        /// </summary>
        public static string PersonInvolved {
            get {
                return ResourceManager.GetString("PersonInvolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefoonnummer.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieuwe wachtwoord herhalen.
        /// </summary>
        public static string RepeatNewPassword {
            get {
                return ResourceManager.GetString("RepeatNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacten.
        /// </summary>
        public static string ReportContacts {
            get {
                return ResourceManager.GetString("ReportContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aangemaakt.
        /// </summary>
        public static string ReportCreated {
            get {
                return ResourceManager.GetString("ReportCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beschrijving.
        /// </summary>
        public static string ReportDescription {
            get {
                return ResourceManager.GetString("ReportDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ip.
        /// </summary>
        public static string ReportIp {
            get {
                return ResourceManager.GetString("ReportIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locatie.
        /// </summary>
        public static string ReportLocation {
            get {
                return ResourceManager.GetString("ReportLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tijd.
        /// </summary>
        public static string ReportTime {
            get {
                return ResourceManager.GetString("ReportTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string ReportType {
            get {
                return ResourceManager.GetString("ReportType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pesten.
        /// </summary>
        public static string ReportTypeBullying {
            get {
                return ResourceManager.GetString("ReportTypeBullying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inbraak.
        /// </summary>
        public static string ReportTypeBurglary {
            get {
                return ResourceManager.GetString("ReportTypeBurglary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vernieling.
        /// </summary>
        public static string ReportTypeDestruction {
            get {
                return ResourceManager.GetString("ReportTypeDestruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digitaal.
        /// </summary>
        public static string ReportTypeDigital {
            get {
                return ResourceManager.GetString("ReportTypeDigital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drugs.
        /// </summary>
        public static string ReportTypeDrugs {
            get {
                return ResourceManager.GetString("ReportTypeDrugs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EHBO.
        /// </summary>
        public static string ReportTypeEHBO {
            get {
                return ResourceManager.GetString("ReportTypeEHBO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vechtpartij.
        /// </summary>
        public static string ReportTypeFighting {
            get {
                return ResourceManager.GetString("ReportTypeFighting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand.
        /// </summary>
        public static string ReportTypeFire {
            get {
                return ResourceManager.GetString("ReportTypeFire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intimidatie.
        /// </summary>
        public static string ReportTypeIntimidation {
            get {
                return ResourceManager.GetString("ReportTypeIntimidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overig.
        /// </summary>
        public static string ReportTypeMisc {
            get {
                return ResourceManager.GetString("ReportTypeMisc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overlast.
        /// </summary>
        public static string ReportTypeNuisance {
            get {
                return ResourceManager.GetString("ReportTypeNuisance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diefstal.
        /// </summary>
        public static string ReportTypeTheft {
            get {
                return ResourceManager.GetString("ReportTypeTheft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voertuigen.
        /// </summary>
        public static string ReportTypeVehicles {
            get {
                return ResourceManager.GetString("ReportTypeVehicles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Agent.
        /// </summary>
        public static string ReportUserAgent {
            get {
                return ResourceManager.GetString("ReportUserAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounttype.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lopende.
        /// </summary>
        public static string StatusInProgress {
            get {
                return ResourceManager.GetString("StatusInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string StatusOpen {
            get {
                return ResourceManager.GetString("StatusOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opgelost.
        /// </summary>
        public static string StatusSolved {
            get {
                return ResourceManager.GetString("StatusSolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overgedragen.
        /// </summary>
        public static string StatusTransferred {
            get {
                return ResourceManager.GetString("StatusTransferred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wat is er gestolen?.
        /// </summary>
        public static string StolenObject {
            get {
                return ResourceManager.GetString("StolenObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tijd.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is het slachtoffer bewusteloos?.
        /// </summary>
        public static string Unconscious {
            get {
                return ResourceManager.GetString("Unconscious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gebruikersnaam.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welke voertuigen heb je gezien?.
        /// </summary>
        public static string Vehicle {
            get {
                return ResourceManager.GetString("Vehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wat is het merk van het voertuig?.
        /// </summary>
        public static string VehicleBrand {
            get {
                return ResourceManager.GetString("VehicleBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welke kleur heeft het voertuig?.
        /// </summary>
        public static string VehicleColor {
            get {
                return ResourceManager.GetString("VehicleColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wat is het kenteken van het voertuig?.
        /// </summary>
        public static string VehicleNumberPlate {
            get {
                return ResourceManager.GetString("VehicleNumberPlate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heeft het voertuig nog andere opvallende kenmerken?.
        /// </summary>
        public static string VehicleProperties {
            get {
                return ResourceManager.GetString("VehicleProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wat voor voertuig is het?.
        /// </summary>
        public static string VehicleType {
            get {
                return ResourceManager.GetString("VehicleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slachtoffer.
        /// </summary>
        public static string Victim {
            get {
                return ResourceManager.GetString("Victim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wie wordt er gepest?.
        /// </summary>
        public static string VictimName {
            get {
                return ResourceManager.GetString("VictimName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waar is het wapen nu?.
        /// </summary>
        public static string WeaponLocation {
            get {
                return ResourceManager.GetString("WeaponLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wat voor wapen heb je gezien?.
        /// </summary>
        public static string WeaponType {
            get {
                return ResourceManager.GetString("WeaponType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wat voor wapen is het dan?.
        /// </summary>
        public static string WeaponTypeOther {
            get {
                return ResourceManager.GetString("WeaponTypeOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wat is er gebeurd?.
        /// </summary>
        public static string WhatHappened {
            get {
                return ResourceManager.GetString("WhatHappened", resourceCulture);
            }
        }
    }
}
