//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lisa.Kiwi.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PageItems {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PageItems() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lisa.Kiwi.Web.Resources.PageItems", typeof(PageItems).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gebouw.
        /// </summary>
        public static string Building {
            get {
                return ResourceManager.GetString("Building", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is er nog meer informatie over de gepeste?.
        /// </summary>
        public static string BullyVictim {
            get {
                return ResourceManager.GetString("BullyVictim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wie is er gepest?.
        /// </summary>
        public static string BullyVictimName {
            get {
                return ResourceManager.GetString("BullyVictimName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wat is er gebeurd?.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U kunt hier uw contactgegevens achterlaten (dit is niet verplicht). Hiermee kunnen wij indien we vragen of opmerkingen hebben contact met uw opnemen..
        /// </summary>
        public static string ContactDescription {
            get {
                return ResourceManager.GetString("ContactDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mailadres van de melder.
        /// </summary>
        public static string ContactEmail {
            get {
                return ResourceManager.GetString("ContactEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naam van de melder.
        /// </summary>
        public static string ContactName {
            get {
                return ResourceManager.GetString("ContactName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefoonnummer van de melder.
        /// </summary>
        public static string ContactPhoneNumber {
            get {
                return ResourceManager.GetString("ContactPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wij willen contact met u opnemen om de melding verder af te handelen. Vul hier uw contactgegevens in..
        /// </summary>
        public static string ContactRequiredDescription {
            get {
                return ResourceManager.GetString("ContactRequiredDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wanneer is de melding gedaan?.
        /// </summary>
        public static string CreatedAt {
            get {
                return ResourceManager.GetString("CreatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tijdstip van de melding.
        /// </summary>
        public static string DateDescription {
            get {
                return ResourceManager.GetString("DateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wat is er aan de hand?.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bedankt voor uw melding.
        /// </summary>
        public static string DoneMessage {
            get {
                return ResourceManager.GetString("DoneMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afbeeldingen verzonden.
        /// </summary>
        public static string FileSuccess {
            get {
                return ResourceManager.GetString("FileSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We sturen hulp..
        /// </summary>
        public static string HelpOnTheWay {
            get {
                return ResourceManager.GetString("HelpOnTheWay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waar is het gebeurd?.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waar {0} {1} is het gebeurd?.
        /// </summary>
        public static string LocationDetailedDescription {
            get {
                return ResourceManager.GetString("LocationDetailedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wie is er bij de melding gemeld?.
        /// </summary>
        public static string Perpetrator {
            get {
                return ResourceManager.GetString("Perpetrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wijzigingen opslaan.
        /// </summary>
        public static string SaveChanges {
            get {
                return ResourceManager.GetString("SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Huidige status van het incident.
        /// </summary>
        public static string StatusDescription {
            get {
                return ResourceManager.GetString("StatusDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wij ondernemen actie..
        /// </summary>
        public static string TakenAction {
            get {
                return ResourceManager.GetString("TakenAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het Meldingstype.
        /// </summary>
        public static string TypeDescription {
            get {
                return ResourceManager.GetString("TypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wilt u dat dit zichtbaar is? (aangevinkt is &quot;Ja&quot;, Leeg is &quot;Nee&quot;.).
        /// </summary>
        public static string VisibleChange {
            get {
                return ResourceManager.GetString("VisibleChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is dit voor iedereen zichtbaar?.
        /// </summary>
        public static string VisibleDescription {
            get {
                return ResourceManager.GetString("VisibleDescription", resourceCulture);
            }
        }
    }
}
