//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Perpetrator {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Perpetrator() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lisa.Kiwi.Web.Resources.Perpetrator", typeof(Perpetrator).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kleding:.
        /// </summary>
        public static string Clothing {
            get {
                return ResourceManager.GetString("Clothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximale leeftijd:.
        /// </summary>
        public static string MaxAge {
            get {
                return ResourceManager.GetString("MaxAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimale leeftijd:.
        /// </summary>
        public static string MinAge {
            get {
                return ResourceManager.GetString("MinAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naam:.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signalement:.
        /// </summary>
        public static string Perpetrators {
            get {
                return ResourceManager.GetString("Perpetrators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geslacht:.
        /// </summary>
        public static string Sex {
            get {
                return ResourceManager.GetString("Sex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Huidskleur:.
        /// </summary>
        public static string SkinColor {
            get {
                return ResourceManager.GetString("SkinColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unieke kenmerken:.
        /// </summary>
        public static string UniqueProp {
            get {
                return ResourceManager.GetString("UniqueProp", resourceCulture);
            }
        }
    }
}
