//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ReportProperties {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReportProperties() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lisa.Kiwi.Web.Resources.ReportProperties", typeof(ReportProperties).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nee.
        /// </summary>
        public static string _False {
            get {
                return ResourceManager.GetString("_False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hier is geen waarde voor ingevuld..
        /// </summary>
        public static string _null {
            get {
                return ResourceManager.GetString("_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ja.
        /// </summary>
        public static string _True {
            get {
                return ResourceManager.GetString("_True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het slachtoffer is.
        /// </summary>
        public static string BullyVictim {
            get {
                return ResourceManager.GetString("BullyVictim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tijd van diefstal.
        /// </summary>
        public static string DateOfTheft {
            get {
                return ResourceManager.GetString("DateOfTheft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verdere beschrijving.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het wordt verhandeld..
        /// </summary>
        public static string DrugsDealing {
            get {
                return ResourceManager.GetString("DrugsDealing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het wordt gebruikt..
        /// </summary>
        public static string DrugsUsing {
            get {
                return ResourceManager.GetString("DrugsUsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het slachtoffer is niet bewusteloos..
        /// </summary>
        public static string FalseFirstAid {
            get {
                return ResourceManager.GetString("FalseFirstAid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aantal betrokkenen.
        /// </summary>
        public static string FightCount {
            get {
                return ResourceManager.GetString("FightCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bestanden.
        /// </summary>
        public static string Files {
            get {
                return ResourceManager.GetString("Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is het slachtoffer bewusteloos?.
        /// </summary>
        public static string IsUnconsious {
            get {
                return ResourceManager.GetString("IsUnconsious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Omschrijving overlast.
        /// </summary>
        public static string NuisanceDescription {
            get {
                return ResourceManager.GetString("NuisanceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestolen voorwerp.
        /// </summary>
        public static string StolenObject {
            get {
                return ResourceManager.GetString("StolenObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het slachtoffer is bewusteloos..
        /// </summary>
        public static string TrueFirstAid {
            get {
                return ResourceManager.GetString("TrueFirstAid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wordt de drugs gebruikt of verhandeld.
        /// </summary>
        public static string UsingOrDealing {
            get {
                return ResourceManager.GetString("UsingOrDealing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voertuig.
        /// </summary>
        public static string Vehicle {
            get {
                return ResourceManager.GetString("Vehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bijzondere kenmerken van het voertuig.
        /// </summary>
        public static string VehicleAdditionalFeatures {
            get {
                return ResourceManager.GetString("VehicleAdditionalFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merk van het voertuig.
        /// </summary>
        public static string VehicleBrand {
            get {
                return ResourceManager.GetString("VehicleBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kleur van het voertuig.
        /// </summary>
        public static string VehicleColor {
            get {
                return ResourceManager.GetString("VehicleColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kenteken van het voertuig.
        /// </summary>
        public static string VehicleNumberPlate {
            get {
                return ResourceManager.GetString("VehicleNumberPlate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type voertuig.
        /// </summary>
        public static string VehicleType {
            get {
                return ResourceManager.GetString("VehicleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informatie over het slachtoffer.
        /// </summary>
        public static string VictimDescription {
            get {
                return ResourceManager.GetString("VictimDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locatie van het wapen.
        /// </summary>
        public static string WeaponLocation {
            get {
                return ResourceManager.GetString("WeaponLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er is een wapen bij betrokken.
        /// </summary>
        public static string WeaponPresent {
            get {
                return ResourceManager.GetString("WeaponPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Om wat voor wapen gaat het.
        /// </summary>
        public static string WeaponType {
            get {
                return ResourceManager.GetString("WeaponType", resourceCulture);
            }
        }
    }
}
